/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSubmitRouteImport } from './routes/_authenticated.submit'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedResumeTailorRouteImport } from './routes/_authenticated.resume-tailor'
import { Route as AuthenticatedRequirementsRouteImport } from './routes/_authenticated.requirements'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated.integrations'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedConsultantsRouteImport } from './routes/_authenticated.consultants'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated.analytics'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSubmitRoute = AuthenticatedSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResumeTailorRoute =
  AuthenticatedResumeTailorRouteImport.update({
    id: '/resume-tailor',
    path: '/resume-tailor',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRequirementsRoute =
  AuthenticatedRequirementsRouteImport.update({
    id: '/requirements',
    path: '/requirements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConsultantsRoute =
  AuthenticatedConsultantsRouteImport.update({
    id: '/consultants',
    path: '/consultants',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/consultants': typeof AuthenticatedConsultantsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/requirements': typeof AuthenticatedRequirementsRoute
  '/resume-tailor': typeof AuthenticatedResumeTailorRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/submit': typeof AuthenticatedSubmitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/consultants': typeof AuthenticatedConsultantsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/requirements': typeof AuthenticatedRequirementsRoute
  '/resume-tailor': typeof AuthenticatedResumeTailorRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/submit': typeof AuthenticatedSubmitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/consultants': typeof AuthenticatedConsultantsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/requirements': typeof AuthenticatedRequirementsRoute
  '/_authenticated/resume-tailor': typeof AuthenticatedResumeTailorRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/submit': typeof AuthenticatedSubmitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/analytics'
    | '/consultants'
    | '/dashboard'
    | '/integrations'
    | '/requirements'
    | '/resume-tailor'
    | '/settings'
    | '/submit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/analytics'
    | '/consultants'
    | '/dashboard'
    | '/integrations'
    | '/requirements'
    | '/resume-tailor'
    | '/settings'
    | '/submit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/analytics'
    | '/_authenticated/consultants'
    | '/_authenticated/dashboard'
    | '/_authenticated/integrations'
    | '/_authenticated/requirements'
    | '/_authenticated/resume-tailor'
    | '/_authenticated/settings'
    | '/_authenticated/submit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/submit': {
      id: '/_authenticated/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof AuthenticatedSubmitRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/resume-tailor': {
      id: '/_authenticated/resume-tailor'
      path: '/resume-tailor'
      fullPath: '/resume-tailor'
      preLoaderRoute: typeof AuthenticatedResumeTailorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/requirements': {
      id: '/_authenticated/requirements'
      path: '/requirements'
      fullPath: '/requirements'
      preLoaderRoute: typeof AuthenticatedRequirementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/consultants': {
      id: '/_authenticated/consultants'
      path: '/consultants'
      fullPath: '/consultants'
      preLoaderRoute: typeof AuthenticatedConsultantsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedConsultantsRoute: typeof AuthenticatedConsultantsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedRequirementsRoute: typeof AuthenticatedRequirementsRoute
  AuthenticatedResumeTailorRoute: typeof AuthenticatedResumeTailorRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSubmitRoute: typeof AuthenticatedSubmitRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedConsultantsRoute: AuthenticatedConsultantsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedRequirementsRoute: AuthenticatedRequirementsRoute,
  AuthenticatedResumeTailorRoute: AuthenticatedResumeTailorRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSubmitRoute: AuthenticatedSubmitRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
